POST http://localhost:3000/auth/user
Content-Type: application/json

{
    "name": "Fred",
    "password": "zxcnivv408440m,nl;3241d54a",
    "role": "admin"
}
###
PUT http://localhost:3000/auth/user
Content-Type: application/json

{
    "_id": "5fa59d6db42a334e40852539",
    "name": "Fred",
    "password": "zxcnivv408440m,nl;3241d54a",
    "role": "basic"
}

###

GET http://localhost:3000/auth

